---
title: "ADHD Adults Meta-Analysis"
format: 
  html:
    embed-resources: true
editor: visual
execute:
  echo: false
  warning: false
  message: false
---


```{r setup}

source("setup.R")
source("create_long_data.R")


```


## Sensitivity and Specificity Meta-Analysis

```{r}
#| results: asis
d$test_description_self_report <- word(d$test_description_self, 1)
d$test_description_peer_rating <- d$test_description_peer


# If you want to clean up any trailing spaces left behind:
d <- d %>%
  dplyr::mutate(
    study = gsub("\\{.*\\}", "", ID),
    study = trimws(study),
    study = ifelse(study == "van de Glind, 2013", "Van de Glind, 2013", study),
    test_description_self_report = test_description_self
  )


```




```{r}
##| fig-width: 14
##| fig-height: 14

inv_logit <- function(x) { exp(x) / (1 + exp(x)) }
logit <- function(x) { log(x / (1 - x)) }

get_i2_un <- function(model) {
  W <- diag(1/model$vi)
  X <- model.matrix(model)
  P <- W - W %*% X %*% solve(t(X) %*% W %*% X) %*% t(X) %*% W
  v_bar <- (model$k - model$p) / sum(diag(P))
  
  i2 <- (model$tau2 / (sum(model$tau2) + v_bar)) * 100
  return(round(i2, 2))
}

plot_diagnostic_meta <- 
  function(
    d, diag_type_name, 
    true_pos, false_neg, 
    true_neg, false_pos,
    instrument_col,
    sens_reported,
    spec_reported
  ) {
    cat(glue::glue("<h2>{diag_type_name}</h2><br>"))
    d[[instrument_col]] <- stringr::word(d[[instrument_col]])
    
   list_dat <- CreateLongData(d = d, true_pos, true_neg, false_pos, false_neg)
   
   dat_sens_spec <- list_dat$dat_sens_spec 
   dat_long <- list_dat$dat_long
   
    # Find studies where calculated value of sens and spec differs from their calculation
    dat_sens_spec_discrepant <- dat_sens_spec %>%
      dplyr::filter(
        abs(round(sens_calculated) - !!sym(sens_reported) ) > 1 |
          abs(round(spec_calculated) - !!sym(spec_reported) ) > 1 
      )
    
    
    # 2. Run Meta-Analysis Model
    res <- metafor::rma.mv(
      yi, vi, mods = ~ outcome - 1, 
                           random = ~ outcome | study,
                           struct = "UN", data = dat_long
                           )
    output_text <- capture.output(print(res))
    cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
    
    i2_results <- get_i2_un(res)
    cat(glue::glue(
      "**I-squared for Sensitivity:** {i2_results[1]}%<p>")
    )    
    
    cat(glue::glue(
      "**I-squared for Specificity:** {i2_results[2]}%<p>")
    )    
    
    # 3. Setup Plotting Layout
    all_studies <- dat_long %>%
      distinct(study) %>%
      # Add the instrument label early so we can sort by it and Clinical
      dplyr::inner_join(
       d %>% dplyr::select(study, Clinical, !!rlang::sym(instrument_col)) 
      ) %>% 
      dplyr::mutate(
        instrument_label = !!rlang::sym(instrument_col),
        CL = ifelse(Clinical == "Clinical", "CL", "")
      ) %>% 
      # SORTING: Instrument (A-Z) and then Study (A-Z)
      # We arrange in ASCENDING order here...
      arrange(instrument_label, study) %>%
      # ...then we assign row_num so that the first item gets the HIGHEST row 
      # (putting it at the top of the plot)
      mutate(row_num = rev(row_number())) 

    
    k_total <- nrow(all_studies)
    cex <- 0.6
    
    layout(matrix(c(1, 2), nrow = 1), widths = c(1.8, 1))
    # 4. Plot Sensitivity
    par(mar = c(5, 4, 3, 1))
    dat_sens_plot <- 
      all_studies %>% 
      left_join(filter(dat_long, outcome == "sens"), by = "study")
    
    metafor::forest(
      dat_sens_plot$yi, vi = dat_sens_plot$vi, slab = dat_sens_plot$study,
      transf = transf.ilogit,
      xlim = c(-1.7, 2), 
      ylim = c(-2, k_total + 3), 
      alim = c(0, 1),
      steps = 5,
      xlab = "Sensitivity",
      rows = all_studies$row_num, header = "Study", 
      main = paste(""), 
      refline = NA, cex = cex)
    
    text(-1, k_total + 2, "Tool", pos = 4, cex = cex, font = 2) 
    text(-1, all_studies$row_num, all_studies$instrument_label, 
         pos = 4, cex = cex
    )
    text(-0.1, k_total + 2, "CL", pos = 4, cex = cex, font = 2) 
    text(-0.1, all_studies$row_num, all_studies$CL, 
         pos = 4, cex = cex
    )
    addpoly(res$beta[1], sei = res$se[1],
            row = -1, transf = transf.ilogit, mlab = "", 
            col = "red", cex = cex
    )
    
    # 5. Plot Specificity
    par(mar = c(5, 1, 3, 2))
    dat_spec_plot <- all_studies %>% 
      left_join(filter(dat_long, outcome == "spec"), by = "study")
    
    metafor::forest(
      dat_spec_plot$yi, 
      vi = dat_spec_plot$vi, 
      slab = NA, 
      transf = transf.ilogit, 
      xlab = "Specificity",
      xlim = c(-0.1, 2), 
      ylim = c(-2, k_total + 3), 
      rows = all_studies$row_num,
      alim = c(0, 1),
      steps = 5,
      header = "", main = "", 
      refline = NA, 
      cex = cex)
    
    addpoly(
      res$beta[2], 
      sei = res$se[2], 
      row = -1, 
      transf = transf.ilogit, 
      mlab = "", col = "red", cex = cex
    )
    
    cat("<h3>Discrepant Studies</h3><br>")
    
    cat("Discrepant studies are those where the value for 
        sensitivity and specificity that we calculate are > 1% different
        than the value that is in the paper.")
    if (nrow(dat_sens_spec_discrepant) == 0) {
      cat("No discrepant studies. <p>")
    } else {
      knitr::kable(dat_sens_spec_discrepant) %>% print()
    }
    
    
    
    ############### Neurotypical only
    cat("<h3>Neurotypical Only</h3><p>")
    
    dat_long$neurotypical_mod <-
      dat_long$Neurotypical == "Neurotypical"
    if (length(unique(dat_long$neurotypical_mod)) == 1) {
      cat("No variation in neurotypical - comparison not progressing.")
    } else {
      res_neurotypical <- metafor::rma.mv(
        yi, vi, 
        mods = ~ neurotypical_mod:outcome - 1,
        random = ~ outcome | study,
        struct = "UN", data = dat_long
      )

    
      output_text <- capture.output(print(res_neurotypical))
      cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
      
      results_tab <- as.data.frame(summary(res_neurotypical)$beta)
      results_tab$ci.lb <- res_neurotypical$ci.lb
      results_tab$ci.ub <- res_neurotypical$ci.ub
        
      # Apply the inverse logit: exp(x) / (1 + exp(x))
      results_transformed <- results_tab %>%
        mutate(
          Estimate_Prob = plogis(V1),
          Lower_CI = plogis(ci.lb),
          Upper_CI = plogis(ci.ub)
        ) %>%
        select(Estimate_Prob, Lower_CI, Upper_CI)
      
      
      print(knitr::kable(results_transformed, digits = 3))
      
      cat("Test of difference in sensitivity for neurotypical vs not<p>")
      output_text <- 
        capture.output(print(anova(res_neurotypical, L = c(-1, 1, 0, 0))))
      cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
 
      cat("Test of difference in specificity for neurotypical vs not<p>")
      output_text <- 
        capture.output(print(anova(res_neurotypical, L = c(0, 0, -1, 1))))
      cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
     }
    rm(res_neurotypical)
    rm(dat_long)
    ########## End neurotypical only
    
    ########## co-N/A vs (co-Anxiety, co-Autism, co-Depression, co-ODD, co-Other, co-SUD)
    cat("<h3>Comorbiditises Only</h3><p>")
    cat("Compare co-NA studies with any other comborbidity. <p>")
    
    dat_long <- CreateLongData(
      d, true_pos, true_neg, false_pos, false_neg)[[1]]
    
    d_comorbids <- d %>%
      dplyr::mutate(
        coNA = co.N.A == "co-N/A",
        has_comorbidity = (
          co.Anxiety == "co-Anxiety" |
          co.Autism == "co-Autism" |
          co.Depression == "co-Depression" |
          co.OCD == "co-OCD" |
          co.Other == "co-Other" |
          co.SUD ==  "co-SUD")
        ) %>%
      dplyr::filter(has_comorbidity | coNA) %>%
      dplyr::mutate(
        coNA = ifelse(is.na(coNA), FALSE, coNA),
        has_comorbidity  = ifelse(is.na(has_comorbidity ), FALSE, has_comorbidity )
      ) %>% 
      # join to long data
      dplyr::select(ID, has_comorbidity) %>%
      dplyr::full_join(
        dat_long, by = "ID"
      ) %>%
      dplyr::filter(!is.na(outcome))
    
      res_comorbidity <- metafor::rma.mv(
        yi, vi, 
        mods = ~ has_comorbidity:outcome - 1,
        random = ~ outcome | study,
        struct = "UN", data = d_comorbids
      )
    output_text <- capture.output(print(res_comorbidity))
    cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
    cat("Test of difference in sensitivity for comorbidity vs not<p>")
    
    output_text <- 
      output_text <- tryCatch({
        capture.output(print(anova(res_comorbidity, L = c(-1, 1, 0, 0))))
      }, error = function(e) {
        return(NA)
      })
    cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
    
    cat("Test of difference in specificity for comorbidity vs not<p>")
    output_text <- 
      output_text <- tryCatch({
        capture.output(print(anova(res_comorbidity, L = c(0, 0, -1, 1))))
      }, error = function(e) {
        return(NA)
      })
    cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")     
    
    rm(dat_long)
    rm(d_comorbids)
    
    
    ############## Compare clinical with neurotypical
    cat("<h3>Neurotypical Only vs Clinical Only</h3><p>")
   
    list_dat <- CreateLongData(data = d, true_pos, true_neg, false_pos, false_neg)
   
    dat_sens_spec <- list_dat$dat_sens_spec 
    dat_long <- list_dat$dat_long
    
    dat_long$neurotypical_mod <-
      dat_long$Neurotypical == "Neurotypical"
    dat_long$clinical_mod <-
      dat_long$Clinical == "Clinical"
    
    dat_long <- dat_long %>% 
      dplyr::filter(neurotypical_mod | clinical_mod) %>%
      dplyr::filter(!(neurotypical_mod & clinical_mod))
    
    res_neuro_clinical <- metafor::rma.mv(
        yi, vi, 
        mods = ~ neurotypical_mod:outcome - 1,
        random = ~ outcome | study,
        struct = "UN", data = dat_long
      )
        output_text <- capture.output(print(res_comorbidity))
    cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
    cat("Test of difference in sensitivity for neurotypical vs clinical <p>")
    
    output_text <- 
      output_text <- tryCatch({
        capture.output(print(anova(res_neuro_clinical, L = c(-1, 1, 0, 0))))
      }, error = function(e) {
        return(NA)
      })
    cat("```\n", paste(output_text, collapse = "\n"), "\n```\n", sep = "")
    
    cat("Test of difference in specificity for neurotypical vs clinical<p>")
    output_text <- 
      output_text <- tryCatch({
        capture.output(print(anova(res_neuro_clinical, L = c(0, 0, -1, 1))))
      }, error = function(e) {
        return(NA)
      })
  }


```

```{r}
#| results: asis
#| ##| fig-width: 14
##| fig-height: 14

#| 
# Define the categories you want to loop through

for (category in categories) {
  # Dynamically construct column names
  tp <- paste0("true_positive_", category)
  fn <- paste0("false_negative_", category)
  tn <- paste0("true_negative_", category)
  fp <- paste0("false_positive_", category)
  inst <- paste0("test_description_", category)
  sens_reported <- paste0("sensitivity_", category)
  spec_reported <- paste0("specificity_", category)
  
  
  # Generate the plot
  plot_diagnostic_meta(
    d = d, 
    diag_type_name = category, 
    true_pos = tp, 
    false_neg = fn, 
    true_neg = tn, 
    false_pos = fp, 
    instrument_col = inst,
    sens_reported,
    spec_reported
  )
}

```
